# Funding platforms for Pulse UI
# Support the development and maintenance of this library

# GitHub Sponsors
github: TSKVenkat

# Support Pulse UI development
custom: ["https://www.buymeacoffee.com/tskvenkat", "https://ko-fi.com/tskvenkat"]