# Funding platforms for Strive UI
# Support the development and maintenance of this library

github: [TSKVenkat]
custom: ["https://pay.google.com/gp/p/ui/pay?pa=tskv.0411@okicici&pn=Venkataraman%20TSK"]