# Funding platforms for Strive UI

github: [TSKVenkat]
patreon: # Replace with a single Patreon username if you have one
open_collective: # Replace with your Open Collective username if you have one
ko_fi: # Replace with a single Ko-fi username if you have one
tidelift: npm/@strive-ui/core
community_bridge: # Replace with a single Community Bridge project-name if you have one
liberapay: # Replace with a single Liberapay username if you have one
issuehunt: # Replace with a single IssueHunt username if you have one
otechie: # Replace with a single Otechie username if you have one
custom: # Replace with up to 4 custom sponsorship URLs if you have them
